language: cpp
compiler: 
  - gcc 
  - clang
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-add-repository -y ppa:beineri/opt-qt571-xenial
  - sudo apt-get update
  - sudo apt-get install -y build-essential qt57-meta-full
  - source /opt/qt57/bin/qt57-env.sh
  
  
install: true

script:
    qmake && make
